import { CurrencyPipe, DatePipe } from '@angular/common';
import { Component, inject, OnInit, signal } from '@angular/core';
import { Installment, Route } from '../../core/models/models';
import { CatalogService } from '../../core/services/catalog.service';
import { OperationsService } from '../../core/services/operations.service';
import { ToastService } from '../../core/services/toast.service';
import { DateTimePipe } from '../../shared/date-time/date-time.pipe';
import { StatusBadgeComponent } from '../../shared/status-badge/status-badge.component';

@Component({selector:'app-portfolio',standalone:true,imports:[CurrencyPipe,DatePipe,DateTimePipe,StatusBadgeComponent],template:`
 <div class="page-heading"><div><h1>Cartera</h1><p>Cuotas pendientes, vencimientos y días de mora en tiempo real.</p></div><button class="btn btn-ghost" (click)="load()">↻ Actualizar mora</button></div>
 <section class="panel"><div class="toolbar"><div class="search"><input placeholder="Buscar préstamo o cliente…" (input)="changeSearch($event)"></div><select (change)="changeState($event)"><option value="">Todos</option><option>Pendiente</option><option>Abono</option><option>Vencida</option></select><select (change)="changeRoute($event)"><option value="">Todas las rutas</option>@for(route of routes();track route.id){<option [value]="route.id">{{route.code}} · {{route.name}}</option>}</select></div>
 <div class="table-wrap"><table><thead><tr><th>Préstamo</th><th>Cliente</th><th>Registrado</th><th>Cuota</th><th>Vencimiento</th><th>Valor</th><th>Pagado</th><th>Pendiente</th><th>Estado</th><th>Días mora</th><th>Ruta</th></tr></thead><tbody>
 @for(item of items();track item.id){<tr><td><strong>{{item.loanNumber}}</strong></td><td>{{item.clientName}}</td><td>{{item.loanCreatedAt|appDateTime}}</td><td># {{item.number}}</td><td>{{item.dueDate|date:'dd/MM/yyyy'}}</td><td class="money">{{item.amount|currency:'COP':'symbol-narrow':'1.0-0'}}</td><td class="money">{{item.paidAmount|currency:'COP':'symbol-narrow':'1.0-0'}}</td><td class="money"><strong>{{item.pendingAmount|currency:'COP':'symbol-narrow':'1.0-0'}}</strong></td><td><app-status-badge [value]="item.status"/></td><td [class.text-red]="item.daysLate>0">{{item.daysLate}}</td><td>{{item.routeName||'—'}}</td></tr>}
 </tbody></table>@if(!items().length){<div class="empty">No hay cuotas pendientes con los filtros seleccionados.</div>}</div><div class="pagination"><span>{{total()}} cuotas pendientes · página {{page()}}</span><div class="buttons"><button [disabled]="page()===1" (click)="go(page()-1)">Anterior</button><button [disabled]="page()*25>=total()" (click)="go(page()+1)">Siguiente</button></div></div></section>`,styles:[`.toolbar select{width:165px}`]})
export class PortfolioComponent implements OnInit{private service=inject(OperationsService);private catalog=inject(CatalogService);private toast=inject(ToastService);private timer?:number;readonly items=signal<Installment[]>([]);readonly routes=signal<Route[]>([]);readonly total=signal(0);readonly page=signal(1);readonly search=signal('');readonly state=signal('');readonly routeId=signal('');ngOnInit(){this.load();this.catalog.routes(true).subscribe(r=>this.routes.set(r))}load(){this.service.portfolio(this.search(),this.page(),25,this.state(),this.routeId()).subscribe({next:r=>{this.items.set(r.items);this.total.set(r.total)},error:e=>this.toast.error(e)})}go(p:number){this.page.set(p);this.load()}changeSearch(e:Event){this.search.set((e.target as HTMLInputElement).value);clearTimeout(this.timer);this.timer=window.setTimeout(()=>{this.page.set(1);this.load()},300)}changeState(e:Event){this.state.set((e.target as HTMLSelectElement).value);this.page.set(1);this.load()}changeRoute(e:Event){this.routeId.set((e.target as HTMLSelectElement).value);this.page.set(1);this.load()}}
