import { Component, inject, OnInit, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Route } from '../../core/models/models';
import { CatalogService } from '../../core/services/catalog.service';
import { OperationsService } from '../../core/services/operations.service';
import { ToastService } from '../../core/services/toast.service';
import { DateTimePipe } from '../../shared/date-time/date-time.pipe';
import { ModalComponent } from '../../shared/modal/modal.component';
import { StatusBadgeComponent } from '../../shared/status-badge/status-badge.component';

@Component({selector:'app-routes',standalone:true,imports:[ReactiveFormsModule,DateTimePipe,ModalComponent,StatusBadgeComponent],template:`
 <div class="page-heading"><div><h1>Rutas de cobro</h1><p>Organiza cobradores, zonas y exporta el recorrido diario.</p></div><div class="actions"><button class="btn btn-ghost" (click)="exportReport(false)">↓ Excel todas</button><button class="btn btn-ghost" [disabled]="!selected()" (click)="exportReport(true)">↓ Excel ruta seleccionada</button><button class="btn btn-secondary" [disabled]="!selected()" (click)="openEdit()">Editar</button><button class="btn btn-primary" (click)="openNew()">＋ Nueva ruta</button></div></div>
 <section class="route-grid">@for(route of routes();track route.id){<button class="panel route" [class.selected]="selected()?.id===route.id" (click)="selected.set(route)" (dblclick)="openEdit()"><div class="route-top"><span>{{route.code}}</span><app-status-badge [value]="route.active?'Activa':'Inactiva'"/></div><h3>{{route.name}}</h3><p>{{route.zone||'Zona sin definir'}}</p><footer><div class="avatar">{{initials(route.collector)}}</div><span>{{route.collector||'Sin cobrador asignado'}}<small>Creada: {{route.createdAt|appDateTime}}</small></span></footer></button>}</section>
 <app-modal [open]="modal()" [title]="editing()?'Editar ruta':'Nueva ruta'" (closed)="modal.set(false)"><form [formGroup]="form"><div class="form-grid"><div class="field span-2"><label class="required">Nombre de la ruta</label><input formControlName="name"></div><div class="field"><label>Cobrador responsable</label><input formControlName="collector"></div><div class="field"><label>Zona</label><input formControlName="zone"></div><div class="field span-2"><label>Descripción</label><textarea rows="3" formControlName="description"></textarea></div>@if(editing()){<div class="field"><label>Estado</label><select formControlName="active"><option [ngValue]="true">Activa</option><option [ngValue]="false">Inactiva</option></select></div>}</div></form><div modal-actions><button class="btn btn-secondary" (click)="modal.set(false)">Cancelar</button><button class="btn btn-success" (click)="save()">Guardar ruta</button></div></app-modal>`,styles:[`
 .route-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.route{padding:18px;text-align:left;border:1px solid #e2e9ef;cursor:pointer}.route.selected{border-color:#1882a1;box-shadow:0 0 0 3px rgba(24,130,161,.1)}.route-top{display:flex;justify-content:space-between;align-items:center}.route-top>span{font-size:10px;font-weight:900;color:#176b87;background:#eaf5f8;border-radius:8px;padding:6px 8px}.route h3{margin:18px 0 5px;font-size:15px}.route p{margin:0;color:#7b8d9b;font-size:11px}.route footer{display:flex;align-items:center;gap:9px;margin-top:20px;padding-top:13px;border-top:1px solid #edf1f4;color:#607789;font-size:10px}.route footer span{display:grid;gap:3px}.route footer small{color:#8495a2;font-size:8px}.avatar{width:28px;height:28px;border-radius:9px;background:#10243e;color:#fff;display:grid;place-items:center;font-size:9px;font-weight:900}@media(max-width:950px){.route-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:580px){.route-grid{grid-template-columns:1fr}}
 `]})
export class RoutesComponent implements OnInit{private service=inject(CatalogService);private operations=inject(OperationsService);private toast=inject(ToastService);private fb=inject(FormBuilder);readonly routes=signal<Route[]>([]);readonly selected=signal<Route|null>(null);readonly modal=signal(false);readonly editing=signal(false);readonly form=this.fb.group({name:['',Validators.required],collector:[''],zone:[''],description:[''],active:[true]});ngOnInit(){this.load()}load(){this.service.routes().subscribe(r=>this.routes.set(r))}initials(name?:string){return(name||'SR').split(' ').slice(0,2).map(p=>p[0]).join('').toUpperCase()}openNew(){this.editing.set(false);this.form.reset({name:'',collector:'',zone:'',description:'',active:true});this.modal.set(true)}openEdit(){const r=this.selected();if(!r)return;this.editing.set(true);this.form.reset({name:r.name,collector:r.collector??'',zone:r.zone??'',description:'',active:r.active});this.modal.set(true)}save(){if(this.form.invalid){this.toast.show('El nombre de la ruta es obligatorio','error');return}const req=this.editing()?this.service.updateRoute(this.selected()!.id,this.form.getRawValue()):this.service.createRoute(this.form.getRawValue());req.subscribe({next:r=>{this.modal.set(false);this.selected.set(r);this.load();this.toast.show('Ruta guardada')},error:e=>this.toast.error(e)})}exportReport(selectedOnly:boolean){const route=selectedOnly?this.selected():null;if(selectedOnly&&!route)return;const date=new Date().toISOString().slice(0,10);this.operations.routeReport(date,route?.id??'').subscribe({next:blob=>{const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=route?`${route.code}-${date}.xlsx`:`rutas-${date}.xlsx`;a.click();URL.revokeObjectURL(url);this.toast.show(route?`Ruta ${route.code} exportada`:'Reporte de todas las rutas generado')},error:e=>this.toast.error(e)})}}
