import { Component, inject, OnInit, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { User } from '../../core/models/models';
import { CatalogService } from '../../core/services/catalog.service';
import { ToastService } from '../../core/services/toast.service';
import { DateTimePipe } from '../../shared/date-time/date-time.pipe';
import { ModalComponent } from '../../shared/modal/modal.component';
import { StatusBadgeComponent } from '../../shared/status-badge/status-badge.component';

@Component({selector:'app-users',standalone:true,imports:[ReactiveFormsModule,DateTimePipe,ModalComponent,StatusBadgeComponent],template:`
 <div class="page-heading"><div><h1>Usuarios</h1><p>Controla quién puede acceder y qué rol tiene dentro del sistema.</p></div><div class="actions"><button class="btn btn-secondary" [disabled]="!selected()" (click)="openEdit()">Editar</button><button class="btn btn-primary" (click)="openNew()">＋ Nuevo usuario</button></div></div>
 <section class="users-grid">@for(user of users();track user.id){<button class="panel user-card" [class.selected]="selected()?.id===user.id" (click)="selected.set(user)" (dblclick)="openEdit()"><div class="avatar">{{initials(user.fullName)}}</div><div><h3>{{user.fullName}}</h3><p>\u0040{{user.username}}</p><div><app-status-badge [value]="user.role"/><app-status-badge [value]="user.active?'Activo':'Inactivo'"/></div><small>Creado: {{user.createdAt|appDateTime}}</small><small>Último ingreso: {{user.lastLoginAt ? (user.lastLoginAt|appDateTime) : 'Nunca'}}</small><small [class.pending-password]="user.mustChangePassword">Cambio de clave: {{user.mustChangePassword?'Pendiente':'Al día'}}</small></div></button>}</section>
 <app-modal [open]="modal()" [title]="editing()?'Editar usuario':'Nuevo usuario'" (closed)="modal.set(false)"><form [formGroup]="form"><div class="form-grid"><div class="field"><label class="required">Usuario</label><input formControlName="username" [readonly]="editing()"></div><div class="field"><label class="required">Nombre completo</label><input formControlName="fullName"></div><div class="field"><label class="required">Rol</label><select formControlName="role"><option>Administrador</option><option>Operador</option></select></div>@if(editing()){<div class="field"><label>Estado</label><select formControlName="active"><option [ngValue]="true">Activo</option><option [ngValue]="false">Inactivo</option></select></div>}<div class="field span-2"><label [class.required]="!editing()">{{editing()?'Nueva contraseña (opcional)':'Contraseña temporal'}}</label><input type="password" formControlName="password"><span class="hint">Mínimo 8 caracteres. El usuario deberá cambiarla.</span></div></div></form><div modal-actions><button class="btn btn-secondary" (click)="modal.set(false)">Cancelar</button><button class="btn btn-success" (click)="save()">Guardar usuario</button></div></app-modal>`,styles:[`
 .users-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.user-card{display:flex;align-items:center;gap:14px;padding:18px;text-align:left;border:1px solid #e2e9ef;cursor:pointer}.user-card.selected{border-color:#1882a1;box-shadow:0 0 0 3px rgba(24,130,161,.1)}.avatar{width:46px;height:46px;border-radius:13px;background:linear-gradient(135deg,#10243e,#176b87);color:#fff;display:grid;place-items:center;font-size:11px;font-weight:900}.user-card h3{font-size:13px;margin:0}.user-card p{font-size:10px;color:#738797;margin:4px 0 8px}.user-card small{display:block;margin-top:6px;color:#7d8f9e;font-size:8px}.user-card small.pending-password{color:#c07a12;font-weight:800}.user-card app-status-badge{margin-right:5px}@media(max-width:850px){.users-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:550px){.users-grid{grid-template-columns:1fr}}
 `]})
export class UsersComponent implements OnInit{private service=inject(CatalogService);private toast=inject(ToastService);private fb=inject(FormBuilder);readonly users=signal<User[]>([]);readonly selected=signal<User|null>(null);readonly modal=signal(false);readonly editing=signal(false);readonly form=this.fb.group({username:['',Validators.required],fullName:['',Validators.required],role:['Operador',Validators.required],active:[true],password:['']});ngOnInit(){this.load()}load(){this.service.users().subscribe({next:r=>this.users.set(r),error:e=>this.toast.error(e)})}initials(name:string){return name.split(' ').slice(0,2).map(p=>p[0]).join('').toUpperCase()}openNew(){this.editing.set(false);this.form.reset({username:'',fullName:'',role:'Operador',active:true,password:''});this.form.controls.password.setValidators([Validators.required,Validators.minLength(8)]);this.modal.set(true)}openEdit(){const u=this.selected();if(!u)return;this.editing.set(true);this.form.reset({username:u.username,fullName:u.fullName,role:u.role,active:u.active,password:''});this.form.controls.password.setValidators([Validators.minLength(8)]);this.modal.set(true)}save(){this.form.controls.password.updateValueAndValidity();if(this.form.invalid){this.form.markAllAsTouched();this.toast.show('Completa los campos obligatorios','error');return}const raw=this.form.getRawValue();const body=this.editing()?{fullName:raw.fullName,role:raw.role,active:raw.active,...(raw.password?{password:raw.password}:{})}:raw;const request=this.editing()?this.service.updateUser(this.selected()!.id,body):this.service.createUser(body);request.subscribe({next:u=>{this.modal.set(false);this.selected.set(u);this.load();this.toast.show('Usuario guardado')},error:e=>this.toast.error(e)})}}
