import { Component, inject, OnInit, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Setting } from '../../core/models/models';
import { CatalogService } from '../../core/services/catalog.service';
import { ToastService } from '../../core/services/toast.service';
import { DateTimePipe } from '../../shared/date-time/date-time.pipe';
import { ModalComponent } from '../../shared/modal/modal.component';

@Component({selector:'app-settings',standalone:true,imports:[ReactiveFormsModule,DateTimePipe,ModalComponent],template:`
 <div class="page-heading"><div><h1>Configuración</h1><p>Estos valores afectan clientes, préstamos y operación del sistema.</p></div><button class="btn btn-secondary" [disabled]="!selected()" (click)="openEdit()">Editar configuración</button></div>
 <section class="panel"><div class="table-wrap"><table><thead><tr><th>Parámetro</th><th>Valor actual</th><th>Tipo</th><th>Nota</th><th>Actualizado</th></tr></thead><tbody>@for(item of settings();track item.id){<tr [class.selected]="selected()?.id===item.id" (click)="selected.set(item)" (dblclick)="openEdit()"><td><strong>{{item.key}}</strong></td><td>{{display(item)}}</td><td>{{item.valueType}}</td><td>{{item.note||'—'}}</td><td>{{item.updatedAt|appDateTime}}</td></tr>}</tbody></table></div></section>
 <app-modal [open]="modal()" title="Editar configuración" (closed)="modal.set(false)"><form [formGroup]="form"><div class="form-grid"><div class="field span-2"><label>Parámetro seleccionado</label><input formControlName="key"><span class="hint">El nombre del parámetro no se puede modificar.</span></div><div class="field span-2"><label class="required">Valor</label><input formControlName="value"></div><div class="field span-2"><label>Nota</label><textarea rows="4" formControlName="note"></textarea></div></div></form><div modal-actions><button class="btn btn-secondary" (click)="modal.set(false)">Cancelar</button><button class="btn btn-success" (click)="save()">Guardar valor</button></div></app-modal>`,styles:[``]})
export class SettingsComponent implements OnInit{private service=inject(CatalogService);private toast=inject(ToastService);private fb=inject(FormBuilder);readonly settings=signal<(Setting&{updatedAt?:string})[]>([]);readonly selected=signal<Setting|null>(null);readonly modal=signal(false);readonly form=this.fb.group({key:[{value:'',disabled:true}],value:['',Validators.required],note:['']});ngOnInit(){this.load()}load(){this.service.settings().subscribe(r=>this.settings.set(r))}display(item:Setting){if(item.key==='TasaInteresDefecto')return`${Number(item.value)*100}%`;return item.value||'Sin valor'}openEdit(){const s=this.selected();if(!s)return;this.form.reset({key:s.key,value:s.value,note:s.note??''});this.modal.set(true)}save(){const s=this.selected();if(!s||this.form.invalid)return;this.service.updateSetting(s.id,{value:this.form.value.value,note:this.form.value.note}).subscribe({next:()=>{this.modal.set(false);this.load();this.toast.show('Configuración actualizada')},error:e=>this.toast.error(e)})}}
